-- =========================================================================
-- 1. CLEAN SLATE: DROP EXISTING TABLES
-- =========================================================================
-- SET FOREIGN_KEY_CHECKS = 0;
-- DROP TABLE IF EXISTS activity_values, activity_fields, daily_logs, weekly_goals, project_categories, password_resets, user_settings, users, default_activity_fields;
-- SET FOREIGN_KEY_CHECKS = 1;

-- =========================================================================
-- 2. SCHEMA: CREATE ALL TABLES
-- =========================================================================
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_settings (
    user_id INT PRIMARY KEY,
    sleep_target DECIMAL(3,1) DEFAULT 7.5,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS password_resets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(150) NOT NULL,
    token VARCHAR(64) NOT NULL,
    expires_at DATETIME NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS project_categories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    category_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE KEY unique_user_category (user_id, category_name)
);

CREATE TABLE IF NOT EXISTS weekly_goals (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    week_start_date DATE NOT NULL,
    task_name VARCHAR(255) NOT NULL,
    task_details TEXT NULL,
    project_category VARCHAR(50) NOT NULL,
    status ENUM('planned', 'in-progress', 'completed') DEFAULT 'planned',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS daily_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    log_date DATE NOT NULL,
    raw_24h_activities TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY unique_user_date (user_id, log_date),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS activity_fields (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    field_name VARCHAR(100) NOT NULL,
    group_heading VARCHAR(100) NOT NULL,
    weight DECIMAL(4,2) DEFAULT 0.00,
    chart_color VARCHAR(20) DEFAULT '#212529',
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS activity_values (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    log_date DATE NOT NULL,
    field_id INT NOT NULL,
    hours DECIMAL(5,2) DEFAULT 0.00,
    UNIQUE KEY unique_user_date_field (user_id, log_date, field_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (field_id) REFERENCES activity_fields(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS default_activity_fields (
    id INT AUTO_INCREMENT PRIMARY KEY,
    field_name VARCHAR(100) NOT NULL,
    group_heading VARCHAR(100) NOT NULL,
    weight DECIMAL(4,2) DEFAULT 0.00,
    chart_color VARCHAR(20) DEFAULT '#212529'
);

-- =========================================================================
-- 3. GLOBAL SETUP: DEFAULT FIELD TEMPLATES FOR NEW SIGNUPS
-- =========================================================================
INSERT INTO default_activity_fields (field_name, group_heading, weight, chart_color) VALUES 
('Personal Work', 'HIGH PRIORITY ACTION', 1.00, '#198754'),
('Skill Development', 'HIGH PRIORITY ACTION', 1.50, '#0d6efd'),
('Office Work', 'OFFICE WORK', 0.00, '#212529'),
('Research / Scrolling', 'DISTRACTION & LEISURE', 0.00, '#ffc107'),
('Entertainment', 'DISTRACTION & LEISURE', -1.00, '#dc3545');

-- =========================================================================
-- 4. DEMO ACCOUNT CREATION (USER ID = 1)
-- =========================================================================

-- Create the Demo User (Password is exactly: demo123)
-- The hash below is a pre-generated bcrypt hash for 'demo123'
INSERT INTO users (id, full_name, email, password_hash) VALUES 
(1, 'Demo Engineer', 'demo@corehour.com', '$2y$10$aUF0XBPWRXDvypnFqNs92.a7XGgvhUaSxiNZgsHER7dtUMdk8ZWXC');

-- Initialize Settings and Categories for User 1
INSERT INTO user_settings (user_id, sleep_target) VALUES (1, 7.5);

INSERT INTO project_categories (user_id, category_name) VALUES 
(1, 'Backend Architecture'), 
(1, 'Frontend React'), 
(1, 'Startup Hustle');

-- Clone the Dynamic Tracking Engine manually for User 1
INSERT INTO activity_fields (id, user_id, field_name, group_heading, weight, chart_color) VALUES 
(1, 1, 'Personal Work', 'HIGH PRIORITY ACTION', 1.00, '#198754'),
(2, 1, 'Skill Development', 'HIGH PRIORITY ACTION', 1.50, '#0d6efd'),
(3, 1, 'Office Work', 'OFFICE WORK', 0.00, '#212529'),
(4, 1, 'Research / Scrolling', 'DISTRACTION & LEISURE', 0.00, '#ffc107'),
(5, 1, 'Entertainment', 'DISTRACTION & LEISURE', -1.00, '#dc3545');

-- Insert 1 Pending Demo Objective
INSERT INTO weekly_goals (user_id, week_start_date, task_name, task_details, project_category, status) VALUES 
(1, DATE_SUB(CURDATE(), INTERVAL WEEKDAY(CURDATE()) DAY), 'Finalize UI Component', 'Ensure the dynamic graph is rendering JSON properly.', 'Frontend React', 'in-progress');

-- =========================================================================
-- 5. DEMO DATA GENERATION: 60 DAYS OF EXECUTION LOGS & GRAPH DATA
-- =========================================================================

-- Generate 60 Days of Daily Notes
INSERT INTO daily_logs (user_id, log_date, raw_24h_activities)
SELECT 1, DATE_SUB(CURDATE(), INTERVAL seq DAY), 
    CASE 
        WHEN MOD(seq, 7) = 0 THEN 'Sunday reset. Planning for the week ahead. Cleaned up inbox.'
        WHEN MOD(seq, 7) = 1 THEN 'Monday momentum. Heavy office work, but managed 2 hours of side project.'
        WHEN MOD(seq, 7) = 6 THEN 'Saturday hustle. Deep work on side business architecture.'
        ELSE 'Standard execution. Balanced office and personal work. Need to watch screen time.'
    END
FROM (
    SELECT 0 AS seq UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL 
    SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL 
    SELECT 20 UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL SELECT 28 UNION ALL SELECT 29 UNION ALL 
    SELECT 30 UNION ALL SELECT 31 UNION ALL SELECT 32 UNION ALL SELECT 33 UNION ALL SELECT 34 UNION ALL SELECT 35 UNION ALL SELECT 36 UNION ALL SELECT 37 UNION ALL SELECT 38 UNION ALL SELECT 39 UNION ALL 
    SELECT 40 UNION ALL SELECT 41 UNION ALL SELECT 42 UNION ALL SELECT 43 UNION ALL SELECT 44 UNION ALL SELECT 45 UNION ALL SELECT 46 UNION ALL SELECT 47 UNION ALL SELECT 48 UNION ALL SELECT 49 UNION ALL 
    SELECT 50 UNION ALL SELECT 51 UNION ALL SELECT 52 UNION ALL SELECT 53 UNION ALL SELECT 54 UNION ALL SELECT 55 UNION ALL SELECT 56 UNION ALL SELECT 57 UNION ALL SELECT 58 UNION ALL SELECT 59 UNION ALL SELECT 60
) AS DaysList;

-- Generate 60 Days for Field 3 (Office Work): 8 hours weekdays, 0 weekends
INSERT INTO activity_values (user_id, log_date, field_id, hours)
SELECT 1, DATE_SUB(CURDATE(), INTERVAL seq DAY), 3, 
    CASE WHEN MOD(seq, 7) IN (0, 6) THEN 0.0 ELSE 8.0 END
FROM (SELECT 0 AS seq UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL SELECT 20 UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL SELECT 28 UNION ALL SELECT 29 UNION ALL SELECT 30 UNION ALL SELECT 31 UNION ALL SELECT 32 UNION ALL SELECT 33 UNION ALL SELECT 34 UNION ALL SELECT 35 UNION ALL SELECT 36 UNION ALL SELECT 37 UNION ALL SELECT 38 UNION ALL SELECT 39 UNION ALL SELECT 40 UNION ALL SELECT 41 UNION ALL SELECT 42 UNION ALL SELECT 43 UNION ALL SELECT 44 UNION ALL SELECT 45 UNION ALL SELECT 46 UNION ALL SELECT 47 UNION ALL SELECT 48 UNION ALL SELECT 49 UNION ALL SELECT 50 UNION ALL SELECT 51 UNION ALL SELECT 52 UNION ALL SELECT 53 UNION ALL SELECT 54 UNION ALL SELECT 55 UNION ALL SELECT 56 UNION ALL SELECT 57 UNION ALL SELECT 58 UNION ALL SELECT 59 UNION ALL SELECT 60) AS DaysList;

-- Generate 60 Days for Field 1 (Personal Work): Higher hours on weekends
INSERT INTO activity_values (user_id, log_date, field_id, hours)
SELECT 1, DATE_SUB(CURDATE(), INTERVAL seq DAY), 1, 
    CASE WHEN MOD(seq, 7) IN (0, 6) THEN 4.5 ELSE 2.0 END
FROM (SELECT 0 AS seq UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL SELECT 20 UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL SELECT 28 UNION ALL SELECT 29 UNION ALL SELECT 30 UNION ALL SELECT 31 UNION ALL SELECT 32 UNION ALL SELECT 33 UNION ALL SELECT 34 UNION ALL SELECT 35 UNION ALL SELECT 36 UNION ALL SELECT 37 UNION ALL SELECT 38 UNION ALL SELECT 39 UNION ALL SELECT 40 UNION ALL SELECT 41 UNION ALL SELECT 42 UNION ALL SELECT 43 UNION ALL SELECT 44 UNION ALL SELECT 45 UNION ALL SELECT 46 UNION ALL SELECT 47 UNION ALL SELECT 48 UNION ALL SELECT 49 UNION ALL SELECT 50 UNION ALL SELECT 51 UNION ALL SELECT 52 UNION ALL SELECT 53 UNION ALL SELECT 54 UNION ALL SELECT 55 UNION ALL SELECT 56 UNION ALL SELECT 57 UNION ALL SELECT 58 UNION ALL SELECT 59 UNION ALL SELECT 60) AS DaysList;

-- Generate 60 Days for Field 2 (Skill Development)
INSERT INTO activity_values (user_id, log_date, field_id, hours)
SELECT 1, DATE_SUB(CURDATE(), INTERVAL seq DAY), 2, 
    CASE WHEN MOD(seq, 3) = 0 THEN 1.5 ELSE 0.5 END
FROM (SELECT 0 AS seq UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL SELECT 20 UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL SELECT 28 UNION ALL SELECT 29 UNION ALL SELECT 30 UNION ALL SELECT 31 UNION ALL SELECT 32 UNION ALL SELECT 33 UNION ALL SELECT 34 UNION ALL SELECT 35 UNION ALL SELECT 36 UNION ALL SELECT 37 UNION ALL SELECT 38 UNION ALL SELECT 39 UNION ALL SELECT 40 UNION ALL SELECT 41 UNION ALL SELECT 42 UNION ALL SELECT 43 UNION ALL SELECT 44 UNION ALL SELECT 45 UNION ALL SELECT 46 UNION ALL SELECT 47 UNION ALL SELECT 48 UNION ALL SELECT 49 UNION ALL SELECT 50 UNION ALL SELECT 51 UNION ALL SELECT 52 UNION ALL SELECT 53 UNION ALL SELECT 54 UNION ALL SELECT 55 UNION ALL SELECT 56 UNION ALL SELECT 57 UNION ALL SELECT 58 UNION ALL SELECT 59 UNION ALL SELECT 60) AS DaysList;

-- Generate 60 Days for Field 4 (Research)
INSERT INTO activity_values (user_id, log_date, field_id, hours)
SELECT 1, DATE_SUB(CURDATE(), INTERVAL seq DAY), 4, 
    CASE WHEN MOD(seq, 4) = 0 THEN 1.0 ELSE 0.5 END
FROM (SELECT 0 AS seq UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL SELECT 20 UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL SELECT 28 UNION ALL SELECT 29 UNION ALL SELECT 30 UNION ALL SELECT 31 UNION ALL SELECT 32 UNION ALL SELECT 33 UNION ALL SELECT 34 UNION ALL SELECT 35 UNION ALL SELECT 36 UNION ALL SELECT 37 UNION ALL SELECT 38 UNION ALL SELECT 39 UNION ALL SELECT 40 UNION ALL SELECT 41 UNION ALL SELECT 42 UNION ALL SELECT 43 UNION ALL SELECT 44 UNION ALL SELECT 45 UNION ALL SELECT 46 UNION ALL SELECT 47 UNION ALL SELECT 48 UNION ALL SELECT 49 UNION ALL SELECT 50 UNION ALL SELECT 51 UNION ALL SELECT 52 UNION ALL SELECT 53 UNION ALL SELECT 54 UNION ALL SELECT 55 UNION ALL SELECT 56 UNION ALL SELECT 57 UNION ALL SELECT 58 UNION ALL SELECT 59 UNION ALL SELECT 60) AS DaysList;

-- Generate 60 Days for Field 5 (Entertainment)
INSERT INTO activity_values (user_id, log_date, field_id, hours)
SELECT 1, DATE_SUB(CURDATE(), INTERVAL seq DAY), 5, 
    CASE WHEN MOD(seq, 5) = 0 THEN 2.5 ELSE 1.0 END
FROM (SELECT 0 AS seq UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL SELECT 20 UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL SELECT 28 UNION ALL SELECT 29 UNION ALL SELECT 30 UNION ALL SELECT 31 UNION ALL SELECT 32 UNION ALL SELECT 33 UNION ALL SELECT 34 UNION ALL SELECT 35 UNION ALL SELECT 36 UNION ALL SELECT 37 UNION ALL SELECT 38 UNION ALL SELECT 39 UNION ALL SELECT 40 UNION ALL SELECT 41 UNION ALL SELECT 42 UNION ALL SELECT 43 UNION ALL SELECT 44 UNION ALL SELECT 45 UNION ALL SELECT 46 UNION ALL SELECT 47 UNION ALL SELECT 48 UNION ALL SELECT 49 UNION ALL SELECT 50 UNION ALL SELECT 51 UNION ALL SELECT 52 UNION ALL SELECT 53 UNION ALL SELECT 54 UNION ALL SELECT 55 UNION ALL SELECT 56 UNION ALL SELECT 57 UNION ALL SELECT 58 UNION ALL SELECT 59 UNION ALL SELECT 60) AS DaysList;

